### ISSUE TITLE
503 error on initializing request

### ISSUE THREAD

**Issue by ohpyupi** [openid/OpenYOLO-Web#73]
Hi,

I have tried testing the API. However, I got a 503 error for every methods, such as `retrieve`, `hint`, or `hintsAvailable`. Should I do additional configuration to use OpenYOLO api? Can anyone help me on this? Please see the error details below.

Thanks

```
Failed to load resource: the server responded with a status of 503 (Service Unavailable)
provider.openyolo.org/?client=http%3A%2F%2Flocalhost%3A8000&id=92e42636609fea47&renderMode=navPopout:1 
```

**Comment by SatoshiOoO** [comment]
Are you using the [Google OneTap](https://developers.google.com/identity/one-tap/web/) or are you setting up your own identity provider? 503 is a server side error while OpenYolo is just a client side framework so it is unlikely the problem is in the OpenYolo code.

Could you provide more context? It looks you are sending the request to provider.openyolo.org which does not seem to exist.

**Comment by ohpyupi** [comment]
I was pointing it to Google OneTap. I guess it is blocked by the Google because I am not whitelisted.
